### ISSUE TITLE
Farmer crashes game when trying to index a nil value

### ISSUE THREAD

**Issue by TotalSuricato** [GuilloryCraft/ExtraCredit#12]
This issue happens when the farmer appears in the shop for me 

`Oops! The game crashed:
[SMODS extracredit "src/essay.lua"]:1668: attempt to index field 'farmer_card' (a nil value)

Additional Context:
Balatro Version: 1.0.1n-FULL
Modded Version: 1.0.0~ALPHA-1220a-STEAMODDED
LÖVE Version: 11.5.0
Lovely Version: 0.5.0-beta6
Steamodded Mods:
    1: Talisman by MathIsFun_, Mathguy24, jenwalter666, cg-223 [ID: Talisman, Version: 2.0.2, Uses Lovely]
        Break Infinity: omeganum
    2: ExtraCredit by CampfireCollective [ID: extracredit, Priority: 1, Version: 1.1.0, Uses Lovely]
Lovely Mods:

Stack Traceback
===============
(3) Lua method 'loc_vars' at file 'src/essay.lua:1668' (from mod with id extracredit)
Local variables:
 self = table: 0x1859a2e8  {alerted:false, loc_vars:function: 0x1831a628, _saved_d_u:true, original_key:farmer (more...)}
 info_queue = table: 0x18320af0  {}
 card = table: 0x18751bc8  {under_overlay:false, debuff:false, click_offset:table: 0x185750e0, STATIONARY:true (more...)}
 (*temporary) = table: 0x18672b98  {}
 (*temporary) = table: 0x18c4d3e8  {1:2}
 (*temporary) = Lua function '?' (defined at line 1815 of chunk functions/misc_functions.lua)
 (*temporary) = nil
 (*temporary) = number: 1
 (*temporary) = string: "attempt to index field 'farmer_card' (a nil value)"
(4) Lua method 'generate_ui' at Steamodded file 'src/game_object.lua:1154' 
Local variables:
 self = table: 0x1859a2e8  {alerted:false, loc_vars:function: 0x1831a628, _saved_d_u:true, original_key:farmer (more...)}
 info_queue = table: 0x18320af0  {}
 card = table: 0x18751bc8  {under_overlay:false, debuff:false, click_offset:table: 0x185750e0, STATIONARY:true (more...)}
 desc_nodes = table: 0x1864e670  {}
 specific_vars = nil
 full_UI_table = table: 0x1864e648  {badges:table: 0x189f9688, info:table: 0x1815f0b0, main:table: 0x1864e670 (more...)}
 target = table: 0x1815f048  {vars:table: 0x1815f070, set:Joker, type:descriptions, nodes:table: 0x1864e670 (more...)}
 res = table: 0x18672b70  {}
(5) Lua method 'generate_UIBox_ability_table' at file 'functions/common_events.lua:2768'
Local variables:
 _c = table: 0x1859a2e8  {alerted:false, loc_vars:function: 0x1831a628, _saved_d_u:true, original_key:farmer (more...)}
 full_UI_table = table: 0x1864e648  {badges:table: 0x189f9688, info:table: 0x1815f0b0, main:table: 0x1864e670 (more...)}
 specific_vars = nil
 card_type = string: "Joker"
 badges = table: 0x189f9688  {force_rarity:true, card_type:Joker}
 hide_desc = nil
 main_start = nil
 main_end = nil
 card = table: 0x18751bc8  {under_overlay:false, debuff:false, click_offset:table: 0x185750e0, STATIONARY:true (more...)}
 first_pass = boolean: true
 desc_nodes = table: 0x1864e670  {}
 name_override = nil
 info_queue = table: 0x18320af0  {}
 loc_vars = table: 0x18320b18  {}
 cfg = table: 0x18059f90  {bonus:0, h_mult:0, extra:table: 0x186a7dc0, x_chips:0, hands_played_at_create:25 (more...)}
(6) Lua method 'hover' at file 'card.lua:4496'
Local variables:
 self = table: 0x18751bc8  {under_overlay:false, debuff:false, click_offset:table: 0x185750e0, STATIONARY:true (more...)}
(7) Lua method 'update' at file 'engine/controller.lua:399'
Local variables:
 self = table: 0x18472c10  {held_button_times:table: 0x184734e0, focus_cursor_stack_level:1, snap_cursor_to:table: 0x185a6560 (more...)}
 dt = number: 0.00415475
(8) Lua upvalue 'gameUpdateRef' at file 'game.lua:2757'
Local variables:
 self = table: 0x1802daa8  {F_GUIDE:false, F_CRASH_REPORTS:false, F_QUIT_BUTTON:true, HUD_tags:table: 0x18706a78 (more...)}
 dt = number: 0.00415475
(9) Lua upvalue 'upd' at Steamodded file 'src/ui.lua:81' 
Local variables:
 self = table: 0x1802daa8  {F_GUIDE:false, F_CRASH_REPORTS:false, F_QUIT_BUTTON:true, HUD_tags:table: 0x18706a78 (more...)}
 dt = number: 0.00415475
(10) Lua method 'update' at file 'main.lua:1748'
Local variables:
 self = table: 0x1802daa8  {F_GUIDE:false, F_CRASH_REPORTS:false, F_QUIT_BUTTON:true, HUD_tags:table: 0x18706a78 (more...)}
 dt = number: 0.00415475
(11) Lua upvalue 'oldupd' at file 'main.lua:987'
Local variables:
 dt = number: 0.00415475
(12) Lua field 'update' at file 'main.lua:1775'
Local variables:
 dt = number: 0.00415475
(13) Lua function '?' at file 'main.lua:931' (best guess)
(14) global C function 'xpcall'
(15) LÖVE function at file 'boot.lua:377' (best guess)
Local variables:
 func = Lua function '?' (defined at line 902 of chunk main.lua)
 inerror = boolean: true
 deferErrhand = Lua function '(LÖVE Function)' (defined at line 348 of chunk [love "boot.lua"])
 earlyinit = Lua function '(LÖVE Function)' (defined at line 355 of chunk [love "boot.lua"])
`

**Comment by GuilloryCraft** [comment]
your lovely is out of date, get 0.6

**Comment by TotalSuricato** [comment]
> your lovely is out of date, get 0.6

i did that however the exact same error ocurred

`Oops! The game crashed:
[SMODS extracredit "src/essay.lua"]:1668: attempt to index field 'farmer_card' (a nil value)

Additional Context:
Balatro Version: 1.0.1n-FULL
Modded Version: 1.0.0~ALPHA-1220a-STEAMODDED
LÖVE Version: 11.5.0
Lovely Version: 0.6.0
Steamodded Mods:
    1: Talisman by MathIsFun_, Mathguy24, jenwalter666, cg-223 [ID: Talisman, Version: 2.0.2, Uses Lovely]
        Break Infinity: omeganum
    2: ExtraCredit by CampfireCollective [ID: extracredit, Priority: 1, Version: 1.1.0, Uses Lovely]
Lovely Mods:

Stack Traceback
===============
(3) Lua method 'loc_vars' at file 'src/essay.lua:1668' (from mod with id extracredit)
Local variables:
 self = table: 0x17286bb0  {alerted:false, loc_vars:function: 0x17388eb0, _saved_d_u:true, original_key:farmer (more...)}
 info_queue = table: 0x178fc970  {}
 card = table: 0x16f7d3b8  {click_offset:table: 0x1791ed78, children:table: 0x170c3080, ambient_tilt:0.2 (more...)}
 (*temporary) = table: 0x17338700  {}
 (*temporary) = table: 0x17338760  {1:2}
 (*temporary) = Lua function '?' (defined at line 1815 of chunk functions/misc_functions.lua)
 (*temporary) = nil
 (*temporary) = number: 1
 (*temporary) = string: "attempt to index field 'farmer_card' (a nil value)"
(4) Lua method 'generate_ui' at Steamodded file 'src/game_object.lua:1154' 
Local variables:
 self = table: 0x17286bb0  {alerted:false, loc_vars:function: 0x17388eb0, _saved_d_u:true, original_key:farmer (more...)}
 info_queue = table: 0x178fc970  {}
 card = table: 0x16f7d3b8  {click_offset:table: 0x1791ed78, children:table: 0x170c3080, ambient_tilt:0.2 (more...)}
 desc_nodes = table: 0x178fc8f8  {}
 specific_vars = nil
 full_UI_table = table: 0x170a50f0  {badges:table: 0x170a5090, info:table: 0x178fc920, main:table: 0x178fc8f8 (more...)}
 target = table: 0x170a5140  {vars:table: 0x173386b0, set:Joker, type:descriptions, nodes:table: 0x178fc8f8 (more...)}
 res = table: 0x173386d8  {}
(5) Lua method 'generate_UIBox_ability_table' at file 'functions/common_events.lua:2808'
Local variables:
 _c = table: 0x17286bb0  {alerted:false, loc_vars:function: 0x17388eb0, _saved_d_u:true, original_key:farmer (more...)}
 full_UI_table = table: 0x170a50f0  {badges:table: 0x170a5090, info:table: 0x178fc920, main:table: 0x178fc8f8 (more...)}
 specific_vars = nil
 card_type = string: "Joker"
 badges = table: 0x170a5090  {force_rarity:true, card_type:Joker}
 hide_desc = nil
 main_start = nil
 main_end = nil
 card = table: 0x16f7d3b8  {click_offset:table: 0x1791ed78, children:table: 0x170c3080, ambient_tilt:0.2 (more...)}
 first_pass = boolean: true
 desc_nodes = table: 0x178fc8f8  {}
 name_override = nil
 info_queue = table: 0x178fc970  {}
 loc_vars = table: 0x170a5118  {}
 cfg = table: 0x16efc348  {bonus:0, h_mult:0, extra:table: 0x16efc370, x_chips:0, hands_played_at_create:25 (more...)}
(6) Lua method 'hover' at file 'card.lua:4502'
Local variables:
 self = table: 0x16f7d3b8  {click_offset:table: 0x1791ed78, children:table: 0x170c3080, ambient_tilt:0.2 (more...)}
(7) Lua method 'update' at file 'engine/controller.lua:399'
Local variables:
 self = table: 0x171fb970  {held_button_times:table: 0x171fc240, focus_cursor_stack_level:1, snap_cursor_to:table: 0x176b6200 (more...)}
 dt = number: 0.00415513
(8) Lua upvalue 'gameUpdateRef' at file 'game.lua:2768'
Local variables:
 self = table: 0x16dbcce0  {F_GUIDE:false, F_CRASH_REPORTS:false, F_QUIT_BUTTON:true, HUD_tags:table: 0x17589a08 (more...)}
 dt = number: 0.00415513
(9) Lua upvalue 'upd' at Steamodded file 'src/ui.lua:81' 
Local variables:
 self = table: 0x16dbcce0  {F_GUIDE:false, F_CRASH_REPORTS:false, F_QUIT_BUTTON:true, HUD_tags:table: 0x17589a08 (more...)}
 dt = number: 0.00415513
(10) Lua method 'update' at file 'main.lua:1749'
Local variables:
 self = table: 0x16dbcce0  {F_GUIDE:false, F_CRASH_REPORTS:false, F_QUIT_BUTTON:true, HUD_tags:table: 0x17589a08 (more...)}
 dt = number: 0.00415513
(11) Lua upvalue 'oldupd' at file 'main.lua:987'
Local variables:
 dt = number: 0.00415513
(12) Lua field 'update' at file 'main.lua:1776'
Local variables:
 dt = number: 0.00415513
(13) Lua function '?' at file 'main.lua:931' (best guess)
(14) global C function 'xpcall'
(15) LÖVE function at file 'boot.lua:377' (best guess)
Local variables:
 func = Lua function '?' (defined at line 902 of chunk main.lua)
 inerror = boolean: true
 deferErrhand = Lua function '(LÖVE Function)' (defined at line 348 of chunk [love "boot.lua"])
 earlyinit = Lua function '(LÖVE Function)' (defined at line 355 of chunk [love "boot.lua"])
`
